[package]
name = "fm-vfs-local"
description = "Local filesystem implementation of the virtual filesystem provider."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
fm-domain.workspace = true
fm-vfs = { path = "../fm-vfs" }
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
